# Generated by Django 2.0.3 on 2018-05-12 08:47

from django.db import migrations, models
import haburas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistuKursu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('place', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[haburas.models.phonenumber_validate])),
                ('sexo', models.CharField(choices=[('m', 'Male'), ('f', 'Famale')], max_length=1)),
                ('cursu', models.CharField(choices=[(1, 'English Basic'), (2, 'Pre-Intermediario'), (3, 'Microsoft Word'), (4, 'Microsoft Excel'), (5, 'Microsoft Power-Point'), (6, 'Microsoft Access'), (7, 'Microsoft Publisher'), (8, 'Linguage Portugues-I'), (9, 'Linguage Portugues-II')], max_length=1)),
            ],
        ),
    ]
