# Generated by Django 2.0.3 on 2018-05-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haburas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registukursu',
            name='cursu',
            field=models.CharField(choices=[(1, 'English Basic'), (2, 'Pre-Intermediario'), (3, 'Microsoft Word'), (4, 'Microsoft Excel'), (5, 'Microsoft Power-Point'), (6, 'Microsoft Access'), (7, 'Microsoft Publisher'), (8, 'Linguage Portugues-I'), (9, 'Linguage Portugues-II')], max_length=30),
        ),
        migrations.AlterField(
            model_name='registukursu',
            name='sexo',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Famale')], max_length=30),
        ),
    ]
