# Generated by Django 2.0.3 on 2018-09-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haburas', '0003_auto_20180513_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='registukursu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
